### ISSUE TITLE
Checklist for the first version

### ISSUE THREAD

**Issue by divyenduz** [graphql/vscode-graphql#1]
### Intro

With this issue I hope to lock down the checklist for the first version and create a place to maintain the context of things/features happening in VSCode/GraphQL Language Service ecosystem that are of concern to us for the features we want to implement. 

**Note:** *`.graphqlconfig` file and its YAML/YML counterparts are referred in this document as `graphql-config file`*

#### General features
- [x] Load the extension on detecting `graphql-config file` at root level or in a parent level directory
- [x] Load the extension in `.graphql`, `.gql files`
- [x] Load the extension on detecting `gql` tag in js, ts, jsx, tsx, vue files
- [ ] ~Load the extension on detecting `graphql-config file` in a sub-directory~
- [x] Support `graphql-config file` with one project and multiple projects
- [x] [Workspaces and multiple root level](https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs) folder support in VSCode
- [x] Test coverage
- [x] Dev setup and usage readme

#### `.graphql`, `.gql` file extension support
- [x] syntax highlighting (type, query, mutation, interface, union, enum, scalar, fragments)
- [x] autocomplete suggestions
- [x] validation against schema
- [x] snippets (interface, type, input, enum, union)
- [x] hover support
- [x] go to definition support

#### `gql` tagged template literal support
- [x] syntax highlighting (type, query, mutation, interface, union, enum, scalar, )
- [x] autocomplete suggestions
- [x] validation against schema
- [x] snippets
- [ ] ~hover support~
- [ ] ~go to definition~
